# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(username: 'demo', email: "demo@demo.com", password: 'password', age: 21)
Project.create(title: "Project: Rad", description: "One Rad Project that combines all the awesome projects into one.", user_id: 1)
Step.create(project_id: 1, title: 'Acquire materials', body: 'some filler text should go here', step_index: 0)
Step.create(project_id: 1, title: 'use amterials', body: 'some filler text should go here!!!!!', step_index: 1)

User.create(username: 'Alfred', email: "demo2@demo.com", password: 'password', age: 21)
Project.create(title: "Basket Weaving", description: "A tutorial about basketweaving for the uninitiated. Now wait! Before you say' why would i ever need to learn how to basket weave', its not a very useful trait, i ask you when is a basket not handy?", user_id: 1)
Step.create(project_id: 2, title: 'Acquire materials', body: 'find a suitable material that you wish to create a basket from. I shall be using fiberglass to create a sturdy basket', step_index: 0)
Step.create(project_id: 2, title: 'Weave it up!', body: 'Assuming you know basic weavmenship, this should be a sinch as I forgot to mention this is an advanced tutorial for master weavesmen, meaning this step is self explainatory', step_index: 1)

User.create(username: 'Nemo', email: "demo3@demo.com", password: 'password', age: 21)
Project.create(title: "Creating a coral home", description: "Today I will be teaching you how to build your own home with just coral and coral accessories! Why you ask? Because coral is a strong structure that can also be your lifelong friend! Also it acts as a backsracther", user_id: 3)
Step.create(project_id: 3, title: 'Acquire materials', body: 'First off, find yourself a coral reef to supply yourself with the neccesary materials. You can just ask them nicely to come along, and they will! If they dont, nudge them a lil, talk to them about their day and then they will!', step_index: 0)
Step.create(project_id: 3, title: 'Build!!', body: 'Bring all your new found friends back to a desired location and let them rest, they have had a long day and need the rest, your home is now done!', step_index: 1)

User.create(username: 'Site Admin', email: "admin3@demo.com", password: 'password123', age: 21)
Project.create(title: "Creating a FullStack Project", description: "You might be wondering, Oh boy, all these jobs I want all seem to want a person with fullstack experience, but I have no idea how to do that! Well you're in luck today because I will outline some neccesary steps to creating a great fullstack project!", user_id: 4)
Step.create(project_id: 4, title: "Finding a project", body: "First step is to find yourself a nice lil sample project to clone, for example, thus fancy smancy site might be a good candidate", step_index: 0)
Step.create(project_id: 4, title: 'Contemplate your life decisions', body: "Unfortunately due to the lack of time, I will be concluding this guide here and will create updates in the future!", step_index: 1)

# user 5
User.create(username: 'Michael Scott', email: "mscott@dunder.mifflin", password: 'babiespassword', age: 46)
Project.create(title: "Somehow I Manage", description: "Nice to meet you all, I am Michael Scott, Regional Manager of Dunder Mifflin Paper Company, and I am excited to bring to you an exclusive never before seen world preview of 'Somehow I Manage', written by your's truly. First off, you might be asking yourself this, 'Michael, how can I trust an article written by technology, after it nearly killed you?' To that I say, everyone deserves a second-second chance. I gave Ryan a second-second chance and look at where he is now. He's my best friend, and that is a wonderful position. But, yes, while technology can steer us in the wrong direction, quite latterally, if it weren't for technology, we wouldn't have Wikipedia, and that is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information. So the internet is quite possibly the truest source of information you're going to get, and quite honestly, should be your only source of information. The information is so true, that college papers have been written using Wikipedia! How crazy is that? Oh and that brings me back to somehow I manage. So in no particular order here is a sneak peak at how you can become just like me, a successful manager.", user_id: 5)

Step.create(project_id: 5, title: "Trust Your Instincts", body: " Nobody wants to be wrong, and quite frankly you should always follow your instincts, no matter how much everyone tells you not to. I followed my insincts once, and lets just say, someone was very lucky. Until everyone kept telling that someone he was doing something wrong. I mean, it was love at first sight. Actually it was ... No, it was when I heard her voice. It was love at first see with my ears. I mean, you dont even need to know what to say. I leave my speaches up to instinct. Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way, and usually it does, all because I trusted my insincts. Yes.", step_index: 0)

Step.create(project_id: 5, title: "Be the cool boss", body: " I love inside jokes. I'd love to be part of one someday. That is why you should always be the cool boss, no matter what. I mean, you're already their boss, so all you need to do is do as many cool things as you can to make your workers think, 'wow, I work for the coolest boss in the world', and they'll work ten times harder, trying to be like you. But that doesn't mean you let things slide. You have to have get enough respect from your employees so that you can say dance, and they say 'How high?' It's a matter of coolness and once you have enough of it, like I do, then you're one step closer to being one of the best bosses, after me. I mean, do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it's not like this compulsive need to be liked, like my need to be praised. In the end, I rather be both feared and loved. I want people to be afraid of how much they love me.", step_index: 1)

Step.create(project_id: 5, title: "Get along with your workers", body: "  There is nothing more important than getting along with your coworkers. It's like I always say, the office Is like a home, and everyone here is family. An office is for not dying. An office is a place to live life to the fullest, to the max. An office is a place where dreams come true. So always Make friends first, make sales second, make love third. In no particular order. If you don't have enough friends, you go to jail. I've seen it on television, and you dont want me to get started on prison. Prison Mike just got out of there and the worst thing about prison was the dementors. I'm not superstitious but I am a little stitious. You don't want to go to prison. But just because everyone's friends in the office doesn't mean you can't be lovers. Some of the best relationships started in my very office. I just have a magical love aura that just brings people together. I don't user it for myself because I would say I kind of have an unfair advantage, because I watch reality dating shows like a hawk, and I learn. I absorb information from the strategies of the winners and the losers. Actually, I probably learn more from the losers. Oh, and Toby is in HR which technically means he works for corporate. So he's not really a part of our family. Also he's divorced, so he's not really a part of his family.", step_index: 2)

Step.create(project_id: 5, title: "Have Passion", body: " I can't stress this enough, in the end, its all about the passion to doing what you love. I love being a manager and being in sales. When I had no other option, I created my own paper company. I knew my ins and outs with paper and I knew it was what I wanted to do. So when I didn't have a job, I started my own paper company, Michael Scott's Paper Company. And even then, it was a tough start. None of my friends believed in me, I didn't know how I was going to get started, and I was broke like a joke. It was hard. That's what she said. But through passion, and customer experience, my team was able to make sales, turn things around, and make a dent in the big guys. It was our passion that brought us our success and thats the only thing you need to be a salesman.", step_index: 3)

# user 6
User.create(username: 'makerdave', email: "m@dave.com", password: 'omgizdave', age: 21)
Project.create(title: "Building your own fan", description: "Ever wanted to get into mechcanical engineering, material sciences, and computer engineering all at once? If thats a yes, then welcome aboard to technical engineering! Here you'll learn how to start the fundamental thinking process that'll seperate you from the crowd. Become a thinking think person instead of thinking science person. Science can only cover so many topics, which is why you should be going over the technical engineering where you learn all of them all at once! Who says you need some fancy degree to a verified engineer, just do everything at the secrecy of your own home amd you'll be just as qualified an engineer as those with degrees! Just remember, you're on your own and I hold no responsibility for whatever damage you may or may not cause due to following this guide. With the formalities out of the way, let us begin.", user_id: 6)

Step.create(project_id: 6, title: "Finding the right parts", body: "First steps first, find the appropriate materials to build your snazzy new fan. For a budget build, you can constuct everything with the basic essentials: Whatever you can find. This can mean you grab cardboard, rubber bands, and straws. But for the fancier people out there, feel free to grab some cardstock or industrial printed ABS frames for the shell of our fan and some type of rotatary motor, like the ones you see on remote controlled cars. You know, it would be easier to just take a remote controlled car and use that. Yeah, go do that instead. I'll wait.", step_index: 0)

Step.create(project_id: 6, title: "Oh, you're back?", body: "That was fast. I was in the middle of baking a pie. I told you to take your time. I was trying to be considerate of how long things can take people and now suddenly I'M the bad guy just because I went ahead and opened up time for you. You know you could've just got your remote car. Well anyways, now that you have that, we'll attach a spoon onto the wheel. Once attached put it into the pie tin and start. What do you mean fan? We were never making a fan, it was always going to be a pie. Look, first you didn't follow instructions, and now you're getting all confused about not building some technical monstrosity, I mean, its getting close to winter, why would you even need a rotating spinner thing that blows wind at a specified direction? I'm not sure why you chose this guide, but I'm sure you're no longer a 'fan'. ", step_index: 1)

Step.create(project_id: 6, title: "Conclusion", body: "And that is how you make a fan. Simple wasn't it? Up until nothing made any sense.", step_index: 2)

# proj 7
Project.create(title: "Building an effective JavaScript Project", description: "Need a fancy JavaScript to impress your friends, family, coworkers, teachers, or anyone else within the general vicinity? Well here's your guy-ed! *ba dum tss* Your JavaScript project will be a free sort of experience for you to explore. Some will make games, others will make data visualization. Your job is to make something interesting and interacting to wow people with your JavaScript. So here are some ideas and why you should consider them in your JavaScript project.", user_id: 4)

Step.create(project_id: 7, title: "Interactiveness", body: "First soff, don't even THINK about difficulty. All of life's challenges are difficult, otherwise it wouldn't be a challenge. Thus, when planning to create a JavaScript project, go with your most difficult idea that you can come up with, for JavaScript project will be an exercise in futility. You will bang your head on this project trying to figure out how exactly JavaScript works and by the end of the day, you'll think you're a bit of a master at this and think you know what you're generally doing. While that may be the case, you'd be incredibly wrong. You only touched the tip of the iceberg of this mountain of a JavaScript project. Assuming you chose the most difficult concept you can mortally think of, you probably have fulfilled the Interactiveness requirement. Fact: All interactive things are immediately challenging. Take Calculus. That's difficult and the tortured soul would most likely be writting out possible solutions and raking their brain trying to figure out exactly how it all works. THAT, is interactive. Engaged and attentive. Make your JavaScript about calculus. Done. Next Topic.", step_index: 0)

Step.create(project_id: 7, title: "Interest", body: "Is your JavaScript idea intriguing? Is it going to blow my socks off at the thought of thinking about what your project can possibly do? Ohhh I hope so, Otherwise it wont be interesting. The number one killer of user interest is the lack of interesting content on their day to day interactions. That is why you should put lots of clickers on your JavaScript project to hide and mystify your content. Something like multiple moving adds that the user will have to click through to discover the real content. This is a guranteed surfire way to hook someone's interest. How do I know this? Well if you cover something up, like a webpage's main content with lots of filler content, like pop-ups, people will irrationally want to know what sort of content you created. It's like saying don't open the box to a group of kids. That is why you should always cover your projects with as many ad's as possible to hide the real content under a blanket of crap, and when the user finally gets to your project, it'le be nearly 100x better than all the ad's they had to deal with getting to it. Additionally, it will be a one way ticket to interet town, so definely do it. Don't just take my word for it, take the word of millions of doctors who hate one specific individual who has discovered the secret to losing weight.", step_index: 1)

Step.create(project_id: 7, title: "Wow factor", body: "Another part of your JavaScript project will be attaining a certain wow factor. You have to ask yourself, what would make someone say, 'awesome' or 'that's so cool!' Assuming you've followed the first two steps, your project should already be close to there. An interesting and interactive project is a recipe for wow. Some ideas to add big wow factors is adding elements that can connect to an individual's general interest. Something that can catch a person off guard and utilize that moment to sell them on how amazing your project is is what you want to do. Other wow factors can include big data. Unexpectedly large data can shock people, especially if its data relevant to the user. For example, information about Spotify listeners or numbers about a specific genre that people listen to can have a certain level of wow factor that makes them think your application is pretty cool.", step_index: 2)

Step.create(project_id: 7, title: "Conclusion", body: "Once you have your topic ideas down, start creating all the moving parts. Plan out your project and create a timeline of how long you expect your parts will take to create and start creating! This part is self explainatory as you just projects can vary from person to person, thus I cant say much. Good luck!", step_index: 1)

# user 7, project 8
User.create(username: 'jhalpert', email: "jhalp@ert.com", password: 'pambeesly', age: 21)
Project.create(title: "Making Jell-O", description: "Simple guide on how to make jell-o. Why jell-o? Why not?", user_id: 7)
Step.create(project_id: 8, title: "Acquire the ingredients", body: "You will need, several boxes of jell-o, and some water. Optionally you can some fresh fruits, but for the purposes of our creation, we will not be using any fruits. You will want lots of jell-o packets, somewhere around 10 3-ounce packets of jell-o. You'll also want a magnitude of 30 cups of hot nd cold water.", step_index: 0)
Step.create(project_id: 8, title: "Starting from the the packet", body: "Pour out the contents of all your jell-o packets into a large mixing bowl with the hot water. You might want to use a large pot for this. The bigger the better. Once you've pour all your contents into the container, start whisking away. Whisk together the jell-o and hot water until no powdery granules remain. wikihow says it'e take about 2-3 minutes, so on a factor of 10, this will probably take you 20-30 minutes. Good luck.", step_index: 1)
Step.create(project_id: 8, title: "Cold on hot", body: "Continue your cooking recipe by adding cold water to your mixture. If you'd like to make the jell-o set faster, use enough ice cubes to fill the cup. Keep in mind that jell-o will start to set rapidly, so you need to work quick. Since we're using more than 6 ounces, use 30 cups of cold water for our mixture.", step_index: 2)
Step.create(project_id: 8, title: "Not according to plan", body: "Pour the mxiture into your desired mold and wait. Once poured, stir your jell-o to clear it of bubbles which will give you the perfect crystal appearance that just look amazing. Remember, you want the recipient to see clearly what is in the jell-o. Feel free to use whatever jell-o mold you would like. The taller the better. You can use a baking pan or bowl. Since our product is going to be enormous, I would suggest getting the fancier of bowls. ", step_index: 3)
Step.create(project_id: 8, title: "Refridgerate", body: "Next up is to cool down your drinks. Stick em in the fridge for at least 2 - 3 days for it to properly solidify. Depending on how cold your fridge or walk-in freezer is, this may even take a week. You can test the jell-o if it's ready by pressing your hand against it. Most likley it'le feel like a watery mess, so don't try this until maybe the 3rd day. If the jell-o sticks to your hand, its not ready. If it sort of sticks to your hand, now would be a good time to put whatever you're trying to submerge into the jell-o. For example, take a stapler and center it just right in your solution. Once there, allow additional cure time.", step_index: 4)
Step.create(project_id: 8, title: "Serve!", body: "You're done, assuming that you didn't listen to these instructions and followed a proper recipe, your jell-o monstrosity should be fully made and beautify.", step_index: 5)



# user 8, project 9
User.create(username: 'Filler', email: "philler@ert.com", password: 'pambeesly', age: 21)

Project.create(title: "How to be an effective salesman, according to my boss", description: "I've been studying my boss for years and I have condensed what I've learned into a very valuable chart. While at first may seem bad, which it actually is, actually holds some interesting nuggets of truth.", user_id:7)
Step.create(project_id: 9, title: "Procrastinate", body: "I've noticed my boss tends to defer all major responsibilities. I know this may sound crazy, especially in a managing position, but he does in fact procrastinate. I've spent a lot of time wondering how this can be an effective strategy or how It's even possible to procrastinate for 6 out of the 8 hours of the workday but what this effectively means is he doesn't have to worry. He knows his business and he is effective when he goes out and does his job. Not everyone might like him for procstinating, but when the time comes, he gets the job done. Albeit it, the decisions he makes could benefit from some more thought", step_index: 0)
Step.create(project_id: 9, title: "Distract Others", body: "Another major thing I've noticed is his ability to distract others. It's almost like a need to be praised by others, even when it's very clear, nobody will praise him. This costs the company time by holding unneccessary meetings about random things in the office and at some points puts a halt on the entire workday. It's not very efficient and despite all the distractions, we all manage to output more sales than any other branch in our company. Maybe it has to do with the fact that we're always behind and constantly need to catch up, or maybe we're all hoping to make enough to get out of here. One thing or another, it oddly works.", step_index: 1)
Step.create(project_id: 9, title: "Critical Thinking", body: "Now this is a minor one, but big. He doesn't do this often but when he does, amazing things do happen. Our boss has a philosophy that business isn't about sales. No, no, no. It's about the people. It's about building a personal connection with our clients and providing clients care and a personal touch which brings them back, time and time again. Anyone can take your money for a product. But not everyone can connect and bring you what you're looking for. Especially not in a time of technology.", step_index: 2)

# user 9, project 10
User.create(username: 'Not-really-NZXT', email: "nzxt@nzxt.com", password: 'pcmasterrace', age: 21)
Project.create(title: "Video Card Installation", description: "Video card installation is one of the easiest aspects of build assembly. Unlike CPU installs, the video card does not have the same type of fragile (and easily bent) pins in its socket. Before starting, for clarity, there is a technical differentiation that should be made.", user_id: 9)
Step.create(project_id: 10, title: "Placement", body: "If your motherboard has multiple PCI Express (PCI-e) slots and you’re considering a multi-GPU or multi-PCIe device configuration, check the motherboard manual to determine which slots are ideal for your specific assortment of devices. Some boards will “multiplex” PCI-e lanes using special chips (called PEX/PLX chips) to get more performance out of devices. In such an instance, you’ll want to make sure you’re getting full use out of that option.", step_index: 0)
Step.create(project_id: 10, title: "Spacing", body: "Determine how many case expansion slots the video card takes. You can do this by lining-up the card in the PCI Express (PCI-e) slot on the motherboard. The most common count is two slots, but some cards will take “2.5” (or even three – though that is exceedingly rare); low-end devices might take only one expansion slot.", step_index: 1)
Step.create(project_id: 10, title: "Open up space", body: "Remove the screws holding the expansion slot in place.", step_index: 2)
Step.create(project_id: 10, title: "Open up more space", body: "Remove the expansion bay covers. You may keep them in a separate box for storage or toss them. They are functionally useless for the remainder of our process, unless you need to repackage the case for some reason (like to sell to a friend in the event you later upgrade).", step_index: 3)

Step.create(project_id: 10, title: "Prep placement", body: "Line the video card’s PCI-e pins and “shoe” up with the slot it’s going into. Like RAM, you’ll here a slight “click” once the card is pressed into place. Use light pressure through the thumbs to mount the video card. If too much force is required, stop and inspect to determine what’s causing the resistance. It may be improperly aligned or there may be a cable in the way.", step_index: 4)
Step.create(project_id: 10, title: "Insertion", body: "If the device uses multiple expansion slots, re-install all of those screws to mount it. Using both (in the event of a two-slot card) screws will significantly reduce “GPU sag,” or the act of the video card weighing itself down in a fashion which makes it un-level.", step_index: 5)
Step.create(project_id: 10, title: "Post installation", body: "After installing, give the video card a slight wiggle to make sure it’s not going anywhere. Ensure the PCI-e slot’s shoe popped into place and is now locked (in the “up” position). Some motherboards, like some of the high-end X99 boards, do not use this same locking mechanism. If that is the case, look at the pins to ensure that they are fully socketed into the PCI-e slot.", step_index: 6)




User.create(username: 'Filler2', email: "phi33r@ert.com", password: 'pambeesly', age: 21)
User.create(username: 'nextpariticipent', email: "p22ler@ert.com", password: 'pambeesly', age: 21)

# user user 11, project 11



# template
# User.create(username: '', email: "", password: '', age: 21)
# Project.create(title: "", description: "", user_id: 4)
# Step.create(project_id: 4, title: "", body: "", step_index: 0)
# Step.create(project_id: 4, title: "", body: "", step_index: 1)

# Project.create(title: "DIY: Book", description: "Create a custom book with these materials.", user_id: 1)
# Project.create(title: "Table Adventures", description: "Dungeons and Dragons table build guide.", user_id: 2)
# Project.create(title: "Walking Coral", description: "COOORAAAAAAAAAAL.", user_id: 3)
# Project.create(title: "Kenta needs kelp!", description: "Ahh! Cave bats!.", user_id: 3)
# Project.create(title: "Gameboy Hoodie", description: "Fits XL Gameboys.", user_id: 4)